<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\HomeController
 */
class HomeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{any}');

        $response->assertOk();
        $response->assertViewIs($request->path());

        // TODO: perform additional assertions
    }

    /**
     * @test - Frontend
     */
    public function root_returns_an_ok_response()
    {
        $this->refreshApplicationWithLocale('en');

        $response = $this->get(route('root'));

        $response->assertStatus(200);
        $response->assertViewIs('frontend.home');

        // TODO: perform additional assertions
    }
}
